#!/usr/bin/env python3
"""Generate epsg_table.go from PROJ's copy of the EPSG registry.

cog names a CRS by its EPSG code only when the GeoKeys do not redefine
it, and two facts about a code decide that: the unit its axes are in
(a key that sets another unit makes a different CRS) and whether EPSG has
deprecated it for a replacement (GDAL reports the replacement). This
script extracts those facts, for the codes a GeoTIFF SHORT key can hold,
from the proj.db in the GDAL container that acceptance/cogcorpus.sh also
uses:

  docker run --rm -v "$PWD:/cog" ghcr.io/osgeo/gdal:ubuntu-small-latest \\
      python3 /cog/epsg_gen.py /cog/epsg_table.go

Only the exceptions are listed: a projected CRS is in metres and a
geographic one in degrees unless the table says otherwise.
"""

import sqlite3
import sys

DB = "/usr/share/proj/proj.db"
db = sqlite3.connect(DB)
q = lambda sql: db.execute(sql).fetchall()  # noqa: E731

version = dict(q("select key, value from metadata"))
epsg_version = version.get("EPSG.VERSION", "?")
proj_version = version.get("PROJ.VERSION", "?")

# The first axis's unit of each EPSG projected and geographic 2D CRS.
proj_units = {
    int(code): int(uom)
    for code, uom in q("""
        select p.code, a.uom_code from projected_crs p
        join axis a on a.coordinate_system_auth_name = p.coordinate_system_auth_name
                   and a.coordinate_system_code = p.coordinate_system_code
                   and a.coordinate_system_order = 1
        where p.auth_name = 'EPSG' and a.uom_auth_name = 'EPSG'""")
    if str(code).isdigit() and int(code) < 65535 and int(uom) != 9001
}
geog_units = {
    int(code): int(uom)
    for code, uom in q("""
        select g.code, a.uom_code from geodetic_crs g
        join axis a on a.coordinate_system_auth_name = g.coordinate_system_auth_name
                   and a.coordinate_system_code = g.coordinate_system_code
                   and a.coordinate_system_order = 1
        where g.auth_name = 'EPSG' and g.type = 'geographic 2D' and a.uom_auth_name = 'EPSG'""")
    # 9122 is "degree (supplier to define representation)", which a
    # GeoTIFF writes as 9102, degree.
    if str(code).isdigit() and int(code) < 65535 and int(uom) not in (9102, 9122)
}
# Deprecated CRSs with exactly one replacement of the same kind.
replaced = {}
for table, code, repl, n in q("""
        select table_name, deprecated_code, min(replacement_code), count(*) from deprecation
        where deprecated_auth_name = 'EPSG' and replacement_auth_name = 'EPSG'
          and table_name in ('projected_crs', 'geodetic_crs')
        group by table_name, deprecated_code"""):
    if n == 1 and str(code).isdigit() and str(repl).isdigit() and int(code) < 65535 and int(repl) < 65535:
        replaced[int(code)] = int(repl)


def packed(m):
    """A sorted list of code<<16 | value, for binary search."""
    return sorted(k << 16 | v for k, v in m.items())


def literal(name, doc, m):
    vals = packed(m)
    lines = [f"// {line}" for line in doc] + [f"var {name} = [...]uint32{{"]
    for i in range(0, len(vals), 8):
        lines.append("\t" + " ".join(f"{v:#010x}," for v in vals[i:i + 8]))
    lines.append("}")
    return "\n".join(lines)


out = [
    "// Code generated by epsg_gen.py from PROJ's proj.db; DO NOT EDIT.",
    f"// EPSG registry {epsg_version}, PROJ {proj_version}.",
    "",
    "package cog",
    "",
    literal("epsgProjectedUnits",
            ["epsgProjectedUnits lists the EPSG projected CRSs whose axes are not in",
             "metres, as code<<16 | the EPSG code of their unit."], proj_units),
    "",
    literal("epsgGeographicUnits",
            ["epsgGeographicUnits lists the EPSG geographic 2D CRSs whose axes are not",
             "in degrees, as code<<16 | the EPSG code of their unit."], geog_units),
    "",
    literal("epsgReplaced",
            ["epsgReplaced lists the EPSG CRSs deprecated in favour of a single",
             "replacement, as code<<16 | the replacement's code."], replaced),
    "",
]
with open(sys.argv[1], "w") as f:
    f.write("\n".join(out))
print(f"EPSG {epsg_version}: {len(proj_units)} projected, {len(geog_units)} geographic, "
      f"{len(replaced)} replaced")
