#!/usr/bin/env python3
"""Write RESULTS.md: one row per corpus file, from a cogcorpus.sh run.

  python3 report.py [../out-corpus/results.json]

Each row gives the file, its writer (the TIFF Software tag where there is
one, otherwise where the file comes from), its features as GDAL reports
them, the outcome, and the cells compared. A file listed in findings.tsv
failed before the reader was fixed; its outcome says "fixed" and names
the finding. It also prints the per-source summary that
../README.md shows.
"""

import csv
import json
import os
import sys
from collections import defaultdict

HERE = os.path.dirname(os.path.abspath(__file__))
RESULTS = sys.argv[1] if len(sys.argv) > 1 else os.path.join(HERE, "..", "out-corpus", "results.json")

FINDINGS = {
    "mask": "internal mask ignored",
    "crs": "EPSG code GDAL does not give",
    "photometric": "YCbCr/CMYK/CIELab read raw, GDAL converts",
    "lzw-old": "old-style LZW",
    "block-tags": "odd strip/tile tags",
    "tile-in-strip-tags": "tiles under StripOffsets",
    "zero-count": "0-byte block with an offset",
    "short-tile": "edge tile cut short",
    "ifd-loop": "IFD chain loops",
    "subifd": "overviews in SubIFDs",
    "nodata-rule": "NoData parsing or matching",
    "nodata-values": "NODATA_VALUES read per band",
    "negative-scale": "negative ScaleY",
    "fillorder": "FillOrder 2",
}
OSGEO = {"usgs": "USGS", "intergraph": "Intergraph", "pci_eg": "PCI", "made_up": "hand-made (listgeo)",
         "spot": "SPOT Image", "zi_imaging": "Z/I Imaging", "other": "ERDAS", "misc": "unknown",
         "GeogToWGS84GeoKey": "unknown", "gdal_eg": "GDAL"}
GROUP = {"gdal-autotest": "GDAL autotest", "libtiff-test": "libtiff test image",
         "libtiff-pics": "libtiff pics", "x-image": "Go x/image testdata",
         "generated-tiffcp": "tiffcp", "generated-rasterio": "rasterio / rio-cogeo",
         "generated-gdal": "GDAL, unusual options"}

findings = {r["case"]: r["finding"] for r in csv.DictReader(open(os.path.join(HERE, "findings.tsv")), delimiter="\t")}
results = json.load(open(RESULTS))


def writer(r):
    path = r["path"]
    group, rest = path.split("/", 1)
    if group == "osgeo-samples":
        base = f"OSGeo sample, {OSGEO.get(rest.split('/')[0], rest.split('/')[0])}"
    elif group == "products":
        base = rest.split("/")[0]
    else:
        base = GROUP.get(group, group)
    sw = (r.get("software") or "").replace("|", "/").replace("\n", " ").strip()
    return f"{base}; {sw[:40]}" if sw else base


def outcome(r):
    s = r["status"]
    text = {"IDENTICAL": "identical", "ALPHA": "identical, alpha as a band", "REFUSED": "refused",
            "BOTH-REFUSE": "refused, GDAL too", "FAIL": "**FAIL**"}[s]
    if s == "REFUSED":
        text += ": " + r["note"].split(": ", 2)[-1].split(" (")[0].replace("|", "/")[:60]
    if r.get("crs_unidentified"):
        text += f" (no EPSG; GDAL {r['crs_unidentified']})"
    if r["name"] in findings:
        text = f"fixed ({FINDINGS[findings[r['name']]]}): {text}"
    return text


rows = ["| File | Writer | Features | Result | Cells compared |", "|---|---|---|---|---:|"]
summary = defaultdict(lambda: defaultdict(int))
for r in sorted(results, key=lambda r: r["path"]):
    feats = (r.get("features") or "").replace("|", "/")
    cells = f"{r['cells']:,}" if r["cells"] else ""
    rows.append(f"| `{r['path']}` | {writer(r)} | {feats} | {outcome(r)} | {cells} |")
    g = r["path"].split("/")[0]
    s = summary[g]
    s["files"] += 1
    s[r["status"]] += 1
    s["cells"] += r["cells"]
    s["fixed"] += r["name"] in findings
    s["nocrs"] += bool(r.get("crs_unidentified"))

with open(os.path.join(HERE, "RESULTS.md"), "w", encoding="utf-8") as f:
    f.write("# Corpus results\n\n")
    f.write("Generated by `report.py` from a run of `../cogcorpus.sh`; see "
            "`../README.md`, \"Reading GeoTIFFs other software wrote\". Features are "
            "GDAL's description of each file. \"fixed\" marks a file that failed before "
            "the reader was fixed, with the finding (`findings.tsv`).\n\n")
    f.write("\n".join(rows) + "\n")

print("| Source | Files | Identical | Refused | GDAL refuses too | Fixed | No EPSG | Failed | Cells compared |")
print("|---|---:|---:|---:|---:|---:|---:|---:|---:|")
tot = defaultdict(int)
for g in sorted(summary):
    s = summary[g]
    ident = s["IDENTICAL"] + s["ALPHA"]
    print(f"| {g} | {s['files']} | {ident} | {s['REFUSED']} | {s['BOTH-REFUSE']} | {s['fixed']} | "
          f"{s['nocrs']} | {s['FAIL']} | {s['cells']:,} |")
    for k in ("files", "REFUSED", "BOTH-REFUSE", "fixed", "nocrs", "FAIL", "cells"):
        tot[k] += s[k]
    tot["ident"] += ident
print(f"| **all** | {tot['files']} | {tot['ident']} | {tot['REFUSED']} | {tot['BOTH-REFUSE']} | {tot['fixed']} | "
      f"{tot['nocrs']} | {tot['FAIL']} | {tot['cells']:,} |")
